### ISSUE TITLE
￼ 0 Votes ﻿﻿Using a keyTab to connect to SQL Server using integratedSecurity;authenticationScheme=JavaKerberos

### ISSUE THREAD

**Issue by joeuw** [Microsoft/mssql-jdbc#391]
I posted my initial query to the wrong place: https://social.msdn.microsoft.com/Forums/en-US/home?forum=sqlsecurity.

﻿﻿﻿﻿﻿﻿I can connect to our SQL Server if I use kinit -k -t /path/to/keyTab principle@DOMAIN.UW.EDU before I run my java code or tomcat application.

I would like to use the keyTab directly so that the code can make a kerberos connection with out having a ticket cached.

I have the following in my jaas.conf file, I also tried the ~/.java.login.config approach:
com.sun.security.auth.module.Krb5Login required
useTicketCache="false"
doNotPrompt="true"
debug="true"
useKeyTab="true"
keyTab="/path/to/keyTab"
principle="﻿﻿principle@DOMAIN.UW.EDU"

I see 'Kerberos Login failed, can not get any of the properties. (If I then do a kinit, I connect.)
I am using the mssql-jdbc-6.1.7 Driver jar.
BTW, thanks for including the source code! I took a look at the jdbc connection url parameters there.
I tried several combinations of parameters and krb options with no success using a keyTab.
Is our krb5.conf a contributing factor? The DOMAIN.UW.EDU is not the default domain.

I figured that I'd try to include a method analogous to the login method in the ConstrainedSample.java  code that is included in the mssql-jdbc-master 6.2.0 github project. I would like the jdbc driver to be configurable to use a kerberos keyTab. I do not see that option in the Driver code. The problem that I have now is that the Driver will not build on my ubuntu 17.04 workstation. There are 5 NoSuchMethodErrors. How should I proceed to build the Driver??
ii maven 3.3.9-4, ii openjdk-8-jdk:amd64 8u131-b11-0ubuntu1.17.04.1, ii junit 3.8.2-8build1

I see from 'Use provided username and password for JavaKerberos', issue 66, that the keyTab method is supported. What am I missing?

**Comment by joeuw** [comment]
I have the keyTab method working. The source code helped. In SQLServerDriver.java, I found: SQLServerDriverStringProperty JAAS_CONFIG_NAME jaasConfigurationName=SQLJDBCDriver.

I was using the name of my java app. That worked when the file cached ticket was available but not using the keyTab.

Thanks again for the Driver and source code!

**Comment by joeuw** [comment]
I got it working.

**Comment by v-afrafi** [comment]
@joeuw  glad it worked out. Thanks!

**Comment by poornics09** [comment]
Hi, can you please help me on how you created keytab file? for the SQL server SPN or UPN ?

**Comment by shadrunov** [comment]
For anyone struggling with running mssql-jdbc with keytab and not ticketCache, don't pass `-Dsun.security.jgss.native=true -Djavax.security.auth.useSubjectCredsOnly=false` options

https://learn.microsoft.com/en-us/sql/connect/jdbc/using-kerberos-integrated-authentication-to-connect-to-sql-server?view=sql-server-ver16#native-platform-gss-integration
