### ISSUE TITLE
NoClassDefFoundError: jdk/net/ExtendedSocketOptions during connection

### ISSUE THREAD

**Issue by dleborgne** [microsoft/mssql-jdbc#2042]
## Driver version
10.2.3

## SQL Server version
Microsoft SQL Azure (RTM) - 12.0.2000.8 

## Client Operating System
CentOS Linux release 7.9.2009 (Core)

## JAVA/JVM version
OpenJDK Runtime Environment (Red_Hat-11.0.17.0.8-2.el7_9)

## Table schema
n/a

## Problem description
When starting on WildFly 24.0.1, using mssql-jdbc-10.2.3.jre11.jar, our Hibernate-based application is unable to connect to the database. Application gets an IJ031084: Unable to create connection error
Caused by: java.lang.NoClassDefFoundError: jdk/net/ExtendedSocketOptions

## Error message/stack trace
```
Caused by: java.lang.NoClassDefFoundError: jdk/net/ExtendedSocketOptions
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.DriverJDBCVersion.setSocketOptions(SQLServerJdbc43.java:66)
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.TDSChannel.open(IOBuffer.java:702)
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3180)
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:2833)
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2671)
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1640)
        at deployment.mssql-jdbc-10.2.3.jre11.jar//com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:936)
```

## Any other details that can be helpful
* Works fine with mssql-jdbc-10.2.1.jre11.jar
* Same error with mssql-jdbc-10.2.2.jre11.jar

**Comment by lilgreenbird** [comment]
hi @dleborgne 

Looks like this is an issue with your Wildfly configuration it can not find `jdk.net.ExtendedSocketOptions`. Older versions of the driver had an issue where it explicitly defined ExtendedSocketOptions that had been fixed in #1953  . Now the driver uses `jdk.net.ExtendedSocketOptions` directly. I believe you will need to add the jdk.net module to Wildfly. We do not support Wildfly directly so if you have questions on how you can do that, please contact their support.

**Comment by dleborgne** [comment]
Hello @lilgreenbird 

Thank you for your answer. It looks like the MongoDB Java driver faced a similar issue and ended up removing the hard dependency to jdk.net, which, I quote, is not actually part of the standard library (though in practice it is usually available).
https://jira.mongodb.org/browse/JAVA-4005.

**Comment by lilgreenbird** [comment]
hi @dleborgne 

Thank you for the reference this looks reasonable we will look into adding the same in our driver.

**Comment by lilgreenbird** [comment]
fixed for 12.2.0

**Comment by sgalles** [comment]
Hello @lilgreenbird 
Do you know when it will be fixed for 10.2 ?
thank you

**Comment by lilgreenbird** [comment]
@David-Engel does this need to be back ported?

**Comment by David-Engel** [comment]
We have no plans to backport this to 10.2.
