### ISSUE TITLE
MS SQL JDBC driver 6.2 does not work with Java 9

### ISSUE THREAD

**Issue by gurmeen7** [Microsoft/mssql-jdbc#549]
## Driver version or jar name
mssql-jdbc-6.2.2.jre8.jar

## SQL Server version
MS SQL 2008

## Client operating system
Windows 7

## Java/JVM version
JDK 9

## Table schema
Please tell us the table schema

## Problem description
My Java program throws a class not found exception because the ms sql driver uses class DataTypeConverter in javax.xml.api module. 

## Expected behavior and actual behavior
MS SQL should not use javax API classes or if it does it should provide a way so that users of the JDBC driver do not have to add knowledge of the java modules that ms sql is using.

## Repro code
Try connecting to ms sql database.

**Comment by cheenamalhotra** [comment]
HI @gurmeen7 
Currently none of our driver released Jars are compatible with JDK9. 

Since JDK9 was recently released, we are currently working on adding support for JDK9 and JDBC4.3 APIs and removing deprecated APIs but that's under development and testing. 

You may try to use our active branch **'JDBC4.3'** for testing your Java program which contains driver source code compatible with JDK9 and is intended to be merged to **'dev'** branch soon. Since the branch is under development and testing, it is susceptible to frequent changes/errors and may not contain recently added driver changes in **'dev'** branch. 

We would appreciate your feedbacks and experience using **'JDBC4.3'** branch and would like to help you with any issues/areas of improvements you may encounter during testing.

**Comment by v-afrafi** [comment]
Hi @gurmeen7,  **[JDBC4.3](https://github.com/Microsoft/mssql-jdbc/tree/JDBC4.3)** branch is now updated and you should be able to build jars with Java 9. Please use that for testing and let us know if you face any issues. Thank you!

**Comment by gurmeen7** [comment]
This link points me to the source code.
I would be helpful if one of you could provide me the JDBC jar to test.

**Comment by gurmeen7** [comment]
Also when I try to compile from git-hub source, I get errors:
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerJdbc43.java:20:
error: duplicate class: com.microsoft.sqlserver.jdbc.DriverJDBCVersion
final class DriverJDBCVersion {
      ^
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:36:
error: cannot find symbol
import java.sql.ShardingKey;
               ^
  symbol:   class ShardingKey
  location: package java.sql
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:5256:
error: cannot find symbol
    public void setShardingKey(ShardingKey shardingKey) throws
SQLFeatureNotSupportedException {
                               ^
  symbol:   class ShardingKey
  location: class SQLServerConnection
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:5261:
error: cannot find symbol
    public void setShardingKey(ShardingKey shardingKey,
                               ^
  symbol:   class ShardingKey
  location: class SQLServerConnection
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:5262:
error: cannot find symbol
            ShardingKey superShardingKey) throws
SQLFeatureNotSupportedException {
            ^
  symbol:   class ShardingKey
  location: class SQLServerConnection
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:5267:
error: cannot find symbol
    public boolean setShardingKeyIfValid(ShardingKey shardingKey,
                                         ^
  symbol:   class ShardingKey
  location: class SQLServerConnection
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:5273:
error: cannot find symbol
    public boolean setShardingKeyIfValid(ShardingKey shardingKey,
                                         ^
  symbol:   class ShardingKey
  location: class SQLServerConnection
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerConnection.java:5274:
error: cannot find symbol
            ShardingKey superShardingKey,
            ^
  symbol:   class ShardingKey
  location: class SQLServerConnection
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java:13:
error: cannot find symbol
import java.sql.ConnectionBuilder;
               ^
  symbol:   class ConnectionBuilder
  location: package java.sql
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java:16:
error: cannot find symbol
import java.sql.ShardingKeyBuilder;
               ^
  symbol:   class ShardingKeyBuilder
  location: package java.sql
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java:1110:
error: cannot find symbol
    public ShardingKeyBuilder createShardingKeyBuilder() throws
SQLException {
           ^
  symbol:   class ShardingKeyBuilder
  location: class SQLServerDataSource
/work/mssql/mssql-jdbc/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerDataSource.java:1115:
error: cannot find symbol
    public ConnectionBuilder createConnectionBuilder() throws SQLException {
           ^
  symbol:   class ConnectionBuilder
  location: class SQLServerDataSource
12 errors
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

**Comment by v-afrafi** [comment]
@gurmeen7 , sure we will provide you the jars soon. In the meantime if you are trying to compile jars, make sure you are using JDK 9 in your environment. Are you getting this output with using` mvn install`? Thanks

**Comment by v-afrafi** [comment]
@gurmeen7 Here are the jars for testing. 
[target.zip](https://github.com/Microsoft/mssql-jdbc/files/1519397/target.zip)

**Comment by gurmeen7** [comment]
Thanks for the jars - they seem to work with Java 9 in my first round of
testing.

**Comment by gurmeen7** [comment]
I used the jre 9 version of jar - does this mean that it will be compatible
with java 8 as well  as java 9 ?

**Comment by v-afrafi** [comment]
@gurmeen7  If you are using .jre9 version of the driver, you will need to use java 8.

**Comment by cheenamalhotra** [comment]
Hi @gurmeen7 do you need any further assistance on this issue? Just to let you know we are currently working on releasing 6.4.0 version of the driver, which would have jre9 jars as well. The PR #601 introduces JDK9 compatibility to the driver.

If we were able to resolve your queries, please close the issue.

**Comment by gurmeen7** [comment]
Hi,
The issue can be closed for now. If I find something with the new jars and
jdk9 - I shall raise a new issue.
Thanks,
Gurmeen
