### ISSUE TITLE
NoClassDefFoundError: com/microsoft/sqlserver/jdbc/StreamInfo

### ISSUE THREAD

**Issue by JDBC-0** [microsoft/mssql-jdbc#2418]
## Driver version
12.6.1

## SQL Server version
Microsoft SQL Server 2019 (RTM-CU25-GDR) (KB5036335) - 15.0.4360.2 (X64)   Mar 19 2024 00:23:01   Copyright (C) 2019 Microsoft Corporation  Enterprise Evaluation Edition (64-bit) on Windows Server 2019 Standard 10.0 <X64> (Build 17763: ) 

## Client Operating System
Windows Server 2019 Standard

## JAVA/JVM version
17.0.8.1 LTS

## Problem description
After Updating from driver version from 12.2.0 to 12.6.1, some SQL queries throw NoClassDefFoundError: com/microsoft/sqlserver/jdbc/StreamInfo. Inspecting the JARs of the driver versions, this StreamInfo class exists in 12.2.0 but not on 12.6.1 anymore!

## Expected behavior
No change of classes or at least  description in driver release notes about this change and how to replace old behaviour.

## Actual behavior
See error message below.

## Error message/stack trace
Unexpected error: java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/StreamInfo
    java.lang.NoClassDefFoundError: com/microsoft/sqlserver/jdbc/StreamInfo
    	at com.microsoft.sqlserver.jdbc.SQLServerStatement$1NextResult.onInfo(SQLServerStatement.java:1636)
    	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:109)
    	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1691)
    	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:1124)

**Comment by JDBC-0** [comment]
V 12.4.1 also worked. I can't find anything when searching for "StreamInfo" in https://github.com/microsoft/mssql-jdbc/releases .

**Comment by David-Engel** [comment]
Are you sure you were running 12.6.1? Your line numbers don't line up with code from any release tags.

StreamInfo appears to be in 12.6.1 but has been deleted in PR #2251, which would only put it in 12.7.0. But again, your stack's line numbers don't align with the code from that tag, either.
https://github.com/microsoft/mssql-jdbc/blob/v12.7.0/src/main/java/com/microsoft/sqlserver/jdbc/SQLServerStatement.java#L1636

Are you running a jar you've built yourself?

**Comment by Jeffery-Wasty** [comment]
Hi @JDBC-0,

We'll be closing this issue in a few days if there is no further reply.

**Comment by JDBC-0** [comment]
It was 12.6.1 .... we reinstalled the driver and then the error didn't occured anymore. Probably corrupt JAR file.
If 12.7.0 will remove StreamInfo, will this be binary compatible or an incompatible change?

**Comment by David-Engel** [comment]
StreamInfo wasn't a public class, so it should remain compatible.
